### ISSUE TITLE
Can I use this book with Flash cs5

### ISSUE THREAD

**Issue by shuhankuang** [blvz/FlexBook#7]
Hi, How can I use the book with CS5?

**Comment by blvz** [comment]
It may be a little tricky if you're not familiar with ActionScript. But you can compile the FlexBook into a SWC and add the pages dynamically. See [this example](https://github.com/blvs/FlexBook-demos-bundle/blob/master/dynamicDemoFlex4/src/Demo.mxml).

Alternatively, you could build the book with Flex and just load the SWF (or SWC) into your regular Flash SWF.
