### ISSUE TITLE
Single pager

### ISSUE THREAD

**Issue by tsendee0409** [blvz/FlexBook#8]
Hi, Is it possible for single page flip?

**Comment by blvz** [comment]
You mean something like iBooks?

**Comment by tsendee0409** [comment]
Yep, Single page view, no doudle view. Like that https://www.youtube.com/watch?v=832uNh7_0Vo

**Comment by blvz** [comment]
You can mask your view and display only one side, giving the same effect. The only downside of this approach is that you would be able to drag pages from right to left, but not from left to right.

But I think with some hacking, that wouldn't be too difficult to achieve either.

**Comment by tsendee0409** [comment]
Okey, thanks for your response
